### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by tanakorn0314** [0xbigz/drift-v2-streamlit#11]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://driftv2.streamlit.app/0xbigz/drift-v2-streamlit/main/app.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by 0xbigz** [comment]
that comes and goes with lots of requests

theres a mirror deploy here: https://driftv2.herokuapp.com/
